name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
      BUCKET: ${{ secrets.BUCKET_NAME }}
      BUCKET_PATH: ${{ secrets.BUCKET_PATH }}
      CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
      NODE_VERSION: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: us-east-2

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ env.BUCKET }}/${{ env.BUCKET_PATH }}/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DIST_ID }} \
            --paths "/*"